//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.19 at 07:26:08 PM BRT 
//


package br.inf.portalfiscal.mdfe;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="irin">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;whiteSpace value="preserve"/>
 *               &lt;maxLength value="10"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="tpEmb">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;whiteSpace value="preserve"/>
 *               &lt;pattern value="[0-9]{2}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="cEmbar">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.portalfiscal.inf.br/mdfe}TString">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="xEmbar">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.portalfiscal.inf.br/mdfe}TString">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="60"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nViag">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;whiteSpace value="preserve"/>
 *               &lt;pattern value="[1-9]{1}[0-9]{0,9}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="cPrtEmb">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.portalfiscal.inf.br/mdfe}TString">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="cPrtDest">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.portalfiscal.inf.br/mdfe}TString">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="prtTrans" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.portalfiscal.inf.br/mdfe}TString">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="60"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="tpNav" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;whiteSpace value="preserve"/>
 *               &lt;enumeration value="0"/>
 *               &lt;enumeration value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="infTermCarreg" maxOccurs="5" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="cTermCarreg">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.portalfiscal.inf.br/mdfe}TString">
 *                         &lt;minLength value="1"/>
 *                         &lt;maxLength value="8"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="xTermCarreg">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.portalfiscal.inf.br/mdfe}TString">
 *                         &lt;minLength value="1"/>
 *                         &lt;maxLength value="60"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="infTermDescarreg" maxOccurs="5" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="cTermDescarreg">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.portalfiscal.inf.br/mdfe}TString">
 *                         &lt;minLength value="1"/>
 *                         &lt;maxLength value="8"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="xTermDescarreg">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.portalfiscal.inf.br/mdfe}TString">
 *                         &lt;minLength value="1"/>
 *                         &lt;maxLength value="60"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="infEmbComb" maxOccurs="30" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="cEmbComb">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.portalfiscal.inf.br/mdfe}TString">
 *                         &lt;minLength value="1"/>
 *                         &lt;maxLength value="10"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="xBalsa">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.portalfiscal.inf.br/mdfe}TString">
 *                         &lt;minLength value="1"/>
 *                         &lt;maxLength value="60"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="infUnidCargaVazia" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="idUnidCargaVazia" type="{http://www.portalfiscal.inf.br/mdfe}TContainer"/>
 *                   &lt;element name="tpUnidCargaVazia">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.portalfiscal.inf.br/mdfe}TString">
 *                         &lt;enumeration value="1"/>
 *                         &lt;enumeration value="2"/>
 *                         &lt;enumeration value="3"/>
 *                         &lt;enumeration value="4"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="infUnidTranspVazia" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="idUnidTranspVazia" type="{http://www.portalfiscal.inf.br/mdfe}TContainer"/>
 *                   &lt;element name="tpUnidTranspVazia">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.portalfiscal.inf.br/mdfe}TString">
 *                         &lt;enumeration value="1"/>
 *                         &lt;enumeration value="2"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "irin",
    "tpEmb",
    "cEmbar",
    "xEmbar",
    "nViag",
    "cPrtEmb",
    "cPrtDest",
    "prtTrans",
    "tpNav",
    "infTermCarreg",
    "infTermDescarreg",
    "infEmbComb",
    "infUnidCargaVazia",
    "infUnidTranspVazia"
})
@XmlRootElement(name = "aquav")
public class Aquav {

    @XmlElement(required = true)
    protected String irin;
    @XmlElement(required = true)
    protected String tpEmb;
    @XmlElement(required = true)
    protected String cEmbar;
    @XmlElement(required = true)
    protected String xEmbar;
    @XmlElement(required = true)
    protected String nViag;
    @XmlElement(required = true)
    protected String cPrtEmb;
    @XmlElement(required = true)
    protected String cPrtDest;
    protected String prtTrans;
    protected String tpNav;
    protected List<Aquav.InfTermCarreg> infTermCarreg;
    protected List<Aquav.InfTermDescarreg> infTermDescarreg;
    protected List<Aquav.InfEmbComb> infEmbComb;
    protected List<Aquav.InfUnidCargaVazia> infUnidCargaVazia;
    protected List<Aquav.InfUnidTranspVazia> infUnidTranspVazia;

    /**
     * Gets the value of the irin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIrin() {
        return irin;
    }

    /**
     * Sets the value of the irin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIrin(String value) {
        this.irin = value;
    }

    /**
     * Gets the value of the tpEmb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTpEmb() {
        return tpEmb;
    }

    /**
     * Sets the value of the tpEmb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTpEmb(String value) {
        this.tpEmb = value;
    }

    /**
     * Gets the value of the cEmbar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCEmbar() {
        return cEmbar;
    }

    /**
     * Sets the value of the cEmbar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCEmbar(String value) {
        this.cEmbar = value;
    }

    /**
     * Gets the value of the xEmbar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXEmbar() {
        return xEmbar;
    }

    /**
     * Sets the value of the xEmbar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXEmbar(String value) {
        this.xEmbar = value;
    }

    /**
     * Gets the value of the nViag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNViag() {
        return nViag;
    }

    /**
     * Sets the value of the nViag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNViag(String value) {
        this.nViag = value;
    }

    /**
     * Gets the value of the cPrtEmb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPrtEmb() {
        return cPrtEmb;
    }

    /**
     * Sets the value of the cPrtEmb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPrtEmb(String value) {
        this.cPrtEmb = value;
    }

    /**
     * Gets the value of the cPrtDest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPrtDest() {
        return cPrtDest;
    }

    /**
     * Sets the value of the cPrtDest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPrtDest(String value) {
        this.cPrtDest = value;
    }

    /**
     * Gets the value of the prtTrans property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrtTrans() {
        return prtTrans;
    }

    /**
     * Sets the value of the prtTrans property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrtTrans(String value) {
        this.prtTrans = value;
    }

    /**
     * Gets the value of the tpNav property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTpNav() {
        return tpNav;
    }

    /**
     * Sets the value of the tpNav property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTpNav(String value) {
        this.tpNav = value;
    }

    /**
     * Gets the value of the infTermCarreg property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the infTermCarreg property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInfTermCarreg().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Aquav.InfTermCarreg }
     * 
     * 
     */
    public List<Aquav.InfTermCarreg> getInfTermCarreg() {
        if (infTermCarreg == null) {
            infTermCarreg = new ArrayList<Aquav.InfTermCarreg>();
        }
        return this.infTermCarreg;
    }

    /**
     * Gets the value of the infTermDescarreg property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the infTermDescarreg property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInfTermDescarreg().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Aquav.InfTermDescarreg }
     * 
     * 
     */
    public List<Aquav.InfTermDescarreg> getInfTermDescarreg() {
        if (infTermDescarreg == null) {
            infTermDescarreg = new ArrayList<Aquav.InfTermDescarreg>();
        }
        return this.infTermDescarreg;
    }

    /**
     * Gets the value of the infEmbComb property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the infEmbComb property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInfEmbComb().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Aquav.InfEmbComb }
     * 
     * 
     */
    public List<Aquav.InfEmbComb> getInfEmbComb() {
        if (infEmbComb == null) {
            infEmbComb = new ArrayList<Aquav.InfEmbComb>();
        }
        return this.infEmbComb;
    }

    /**
     * Gets the value of the infUnidCargaVazia property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the infUnidCargaVazia property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInfUnidCargaVazia().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Aquav.InfUnidCargaVazia }
     * 
     * 
     */
    public List<Aquav.InfUnidCargaVazia> getInfUnidCargaVazia() {
        if (infUnidCargaVazia == null) {
            infUnidCargaVazia = new ArrayList<Aquav.InfUnidCargaVazia>();
        }
        return this.infUnidCargaVazia;
    }

    /**
     * Gets the value of the infUnidTranspVazia property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the infUnidTranspVazia property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInfUnidTranspVazia().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Aquav.InfUnidTranspVazia }
     * 
     * 
     */
    public List<Aquav.InfUnidTranspVazia> getInfUnidTranspVazia() {
        if (infUnidTranspVazia == null) {
            infUnidTranspVazia = new ArrayList<Aquav.InfUnidTranspVazia>();
        }
        return this.infUnidTranspVazia;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="cEmbComb">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.portalfiscal.inf.br/mdfe}TString">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="10"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="xBalsa">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.portalfiscal.inf.br/mdfe}TString">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="60"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cEmbComb",
        "xBalsa"
    })
    public static class InfEmbComb {

        @XmlElement(required = true)
        protected String cEmbComb;
        @XmlElement(required = true)
        protected String xBalsa;

        /**
         * Gets the value of the cEmbComb property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCEmbComb() {
            return cEmbComb;
        }

        /**
         * Sets the value of the cEmbComb property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCEmbComb(String value) {
            this.cEmbComb = value;
        }

        /**
         * Gets the value of the xBalsa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getXBalsa() {
            return xBalsa;
        }

        /**
         * Sets the value of the xBalsa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setXBalsa(String value) {
            this.xBalsa = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="cTermCarreg">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.portalfiscal.inf.br/mdfe}TString">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="8"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="xTermCarreg">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.portalfiscal.inf.br/mdfe}TString">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="60"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cTermCarreg",
        "xTermCarreg"
    })
    public static class InfTermCarreg {

        @XmlElement(required = true)
        protected String cTermCarreg;
        @XmlElement(required = true)
        protected String xTermCarreg;

        /**
         * Gets the value of the cTermCarreg property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCTermCarreg() {
            return cTermCarreg;
        }

        /**
         * Sets the value of the cTermCarreg property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCTermCarreg(String value) {
            this.cTermCarreg = value;
        }

        /**
         * Gets the value of the xTermCarreg property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getXTermCarreg() {
            return xTermCarreg;
        }

        /**
         * Sets the value of the xTermCarreg property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setXTermCarreg(String value) {
            this.xTermCarreg = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="cTermDescarreg">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.portalfiscal.inf.br/mdfe}TString">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="8"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="xTermDescarreg">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.portalfiscal.inf.br/mdfe}TString">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="60"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cTermDescarreg",
        "xTermDescarreg"
    })
    public static class InfTermDescarreg {

        @XmlElement(required = true)
        protected String cTermDescarreg;
        @XmlElement(required = true)
        protected String xTermDescarreg;

        /**
         * Gets the value of the cTermDescarreg property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCTermDescarreg() {
            return cTermDescarreg;
        }

        /**
         * Sets the value of the cTermDescarreg property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCTermDescarreg(String value) {
            this.cTermDescarreg = value;
        }

        /**
         * Gets the value of the xTermDescarreg property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getXTermDescarreg() {
            return xTermDescarreg;
        }

        /**
         * Sets the value of the xTermDescarreg property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setXTermDescarreg(String value) {
            this.xTermDescarreg = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="idUnidCargaVazia" type="{http://www.portalfiscal.inf.br/mdfe}TContainer"/>
     *         &lt;element name="tpUnidCargaVazia">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.portalfiscal.inf.br/mdfe}TString">
     *               &lt;enumeration value="1"/>
     *               &lt;enumeration value="2"/>
     *               &lt;enumeration value="3"/>
     *               &lt;enumeration value="4"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "idUnidCargaVazia",
        "tpUnidCargaVazia"
    })
    public static class InfUnidCargaVazia {

        @XmlElement(required = true)
        protected String idUnidCargaVazia;
        @XmlElement(required = true)
        protected String tpUnidCargaVazia;

        /**
         * Gets the value of the idUnidCargaVazia property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIdUnidCargaVazia() {
            return idUnidCargaVazia;
        }

        /**
         * Sets the value of the idUnidCargaVazia property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIdUnidCargaVazia(String value) {
            this.idUnidCargaVazia = value;
        }

        /**
         * Gets the value of the tpUnidCargaVazia property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTpUnidCargaVazia() {
            return tpUnidCargaVazia;
        }

        /**
         * Sets the value of the tpUnidCargaVazia property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTpUnidCargaVazia(String value) {
            this.tpUnidCargaVazia = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="idUnidTranspVazia" type="{http://www.portalfiscal.inf.br/mdfe}TContainer"/>
     *         &lt;element name="tpUnidTranspVazia">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.portalfiscal.inf.br/mdfe}TString">
     *               &lt;enumeration value="1"/>
     *               &lt;enumeration value="2"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "idUnidTranspVazia",
        "tpUnidTranspVazia"
    })
    public static class InfUnidTranspVazia {

        @XmlElement(required = true)
        protected String idUnidTranspVazia;
        @XmlElement(required = true)
        protected String tpUnidTranspVazia;

        /**
         * Gets the value of the idUnidTranspVazia property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIdUnidTranspVazia() {
            return idUnidTranspVazia;
        }

        /**
         * Sets the value of the idUnidTranspVazia property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIdUnidTranspVazia(String value) {
            this.idUnidTranspVazia = value;
        }

        /**
         * Gets the value of the tpUnidTranspVazia property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTpUnidTranspVazia() {
            return tpUnidTranspVazia;
        }

        /**
         * Sets the value of the tpUnidTranspVazia property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTpUnidTranspVazia(String value) {
            this.tpUnidTranspVazia = value;
        }

    }

}
